### ISSUE TITLE
broken pagination

### ISSUE THREAD

**Issue by thilonel** [homeaway/homeaway_api_ruby#18] opened 2017-02-10 13:07 UTC
The account I tested with has 51 listings, the default page size was 10, auto_pagination is on.

## FAIL
```ruby
listing_ids = []
10.times do |i|
  listing_ids[i] = []
  api.my_listings.each { |listing| listing_ids[i] << listing.listingId }
end
```

Here, listings were returned multiple times and hence the unique size of the array was varying, which means that they were left out all the time.
Uniq size varied between 37 and 42.

## SUCCESS
```ruby
listing_ids = []
10.times do |i|
  listing_ids[i] = []
  api.my_listings(page_size: 100).each { |listing| listing_ids[i] << listing.listingId }
end
```

Here all of the arrays returned 51 for uniq size, and there were no diffs between them in content.

The problem is, that we need pagination for big accounts...

Please fix this ASAP! 🙂

**Comment by cemeyer2** [comment] 2017-02-10 17:27
Hi @thilonel 

I attempted to recreate your bug report with the following rspec test using login credentials that were associated with an owner account which has over 60 listings, but was unable to:

```ruby
  it 'gets a consistent number of listings when auto-paginating' do
    listing_ids = []
    10.times do |i|
      listing_ids[i] = []
      @client.my_listings.each { |listing| listing_ids[i] << listing.listingId }
    end
    expect(listing_ids.map {|arr| arr.size}.uniq.count == 1 ).to be_truthy
  end
```

If this is still reproducible on your end, can you reach out to me directly via email at cmeyer@homeaway.com and provide me with 1 of the listing ids that is associated with the particular owner that you are seeing this behavior on. I can then attempt to recreate in our staging environment.

Thanks!

**Comment by thilonel** [comment] 2017-02-15 12:41
I've sent an email.

**Comment by cemeyer2** [comment] 2017-02-16 17:05
Hi @thilonel 

I was unable to reproduce your issue. Do you have an approximate timeframe for when you were seeing this problem? HomeAway had scheduled production maintenance on 2/9/17 which might have caused this transient issue. Are you still able to reproduce this problem?

Also, I would suggest adding a sort onto the `my_listings` call so that the order that the data is sent back will be deterministic.

Thanks!

**Comment by cemeyer2** [comment] 2017-02-25 20:17
closing this out, please reopen if you encounter it in the future

**Closed as completed by cemeyer2** 2017-02-25 20:17 UTC

**Comment by thilonel** [comment] 2018-01-05 12:25
This is still an issue, and if by default the results are not sorted by a unique identifier, then the cause is evident.

> Also, I would suggest adding a sort onto the my_listings call so that the order that the data is sent back will be deterministic.

@cemeyer2 how can I sort in that way? I was looking at: https://github.com/homeaway/homeaway_api_ruby/blob/master/lib/homeaway/api/domain/my_listings.rb#L33 but non of the options seem unique.

Also I couldn't figure out how to use this. `api.my_listings(sort_by: "updated:DESC")` gives a bad request error.
